London class 8/selchuk karakus
CodeYourFuture/HTML-CSS-Module-Project pull request #293
Opened 2021-11-17 19:44 UTC by Selchuk-Karakus

**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name: Selchuk Karakus
- Your City: London Class 8
- Your Slack Name: Selchuk Karakus

# Homework Details

- Module: HTML/CSS
- Week: Week 2

# Notes

- What did you find easy?
HTML has become second nature in a way, It's easy to read and write especially since the introduction of semantic tags.
- What did you find hard?
Nothing is easy but then again nothing is hard either.  I believe It's just a matter of practice. 
- What do you still not understand?
At this stage, I cant think of anything that we covered that I feel uncomfortable with. So far so good.
- Any other notes?
Some assignments are not very clear.  I wonder if this is done on purpose?

2021-11-18 19:51 UTC, JoeWeate commented on css/style.css
> +.header__logo {
Only use 1 underscore, ".header_logo"

2021-11-18 19:52 UTC, JoeWeate commented on css/style.css
> +  color: var(--orange-dark);
very good use!

2021-11-18 19:56 UTC, JoeWeate commented on css/style.css
> +.heading__underMainImage,
Instead of creating two of the same classes with different names, you should rename to one class like ".primary-text"

2021-11-18 20:02 UTC, JoeWeate commented on css/style.css
> +  .advert__section .btn {
Id more this .advert-section underneath the other advert-section tag. Makes it easier to follow

2021-11-18 20:03 UTC, JoeWeate commented on css/style.css
> +.advert__section {
If you add `overflow: hidden;` you'll be able to see how the browser will not longer overflow blank space on the right hand side (you shouldn't be able to scroll left and right, it's a bad user experience). 

Add that to see what it should feel like, then play around with the child components to get the two items centered.

2021-11-18 20:11 UTC, JoeWeate commented
Very good job Selchuk, I'm impressed! I would only recommend one change (related to the overflow issue in the advert section) other than that all the other comments are just tiny gotcha improvements! ++

Moving forward I would try to start thinking of ways you could have improved your className usage as to not have to create a new css declaration for every html, since that can get very long very quick. ++

2021-11-18 20:12 UTC, JoeWeate requested changes

2021-11-18 20:12 UTC, JoeWeate commented on css/style.css
> +  padding: 0 422px;
(This padding  is  what's causing the overflow on the X-axis.) Changing the width:50% and centering the items should give you your ideal solution!

2021-11-18 20:12 UTC, JoeWeate commented on index.html
> +		<section class="advert__section">
This section overflows a little bit on the X-Axis! See https://github.com/CodeYourFuture/HTML-CSS-Coursework-Week2/pull/293/files#r752585609

2021-12-03 17:35 UTC, craig-dsilva commented
Hi @Selchuk-Karakus, I have reviewed your PR and it's really nice. Could you please review mine? Thanks.

2021-12-03 17:41 UTC, craig-dsilva commented on css/style.css
> +}
Good use of handy CSS variables

2021-12-03 17:42 UTC, craig-dsilva commented on css/style.css
> +}
Good use of a flexbox

2021-12-03 17:45 UTC, craig-dsilva commented
Hi @Selchuk-Karakus, I have reviewed you code and it's nicely done.

2023-09-12 08:45 UTC, closed without merging