London Class 8 - Yigit Demirer - HTML/CSS - Week 2
CodeYourFuture/HTML-CSS-Module-Project pull request #325
Opened 2021-11-19 22:37 UTC by YDemirer

**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name: Yigit Demirer
- Your City: London
- Your Slack Name: YDemirer

# Homework Details

- Module: HTML/CSS
- Week: 2

# Notes

- What did you find easy?
Using semantic HTML tags
Creating links, buttons, and adding images

- What did you find hard?
Nesting containers

- What do you still not understand?

- Any other notes?

2021-11-21 12:52 UTC, moneyinthesky commented
Hey @YDemirer, the end result looks great! Just a couple of points for feedback:
- I like how you used some semantic tags like header, footer and main. Do you think you could use any other tags like this? Maybe section?
- In the future, it might be a good idea to reference these background images (like first-background.jpg) in the CSS, and then you can avoid using position: absolute. I think we had this discussion in yesterday's class.

2021-11-26 10:21 UTC, YDemirer commented
> Hey @YDemirer, the end result looks great! Just a couple of points for feedback:
> 
> * I like how you used some semantic tags like header, footer and main. Do you think you could use any other tags like this? Maybe section?
> * In the future, it might be a good idea to reference these background images (like first-background.jpg) in the CSS, and then you can avoid using position: absolute. I think we had this discussion in yesterday's class.

I am so sorry! I've only just seen your feedback. I will work on the points you mentioned. Thanks a lot.

2021-11-27 17:09 UTC, moneyinthesky commented on pages/store.html
> +          <form>
Nicely laid out form, well done.

2021-11-27 17:09 UTC, moneyinthesky commented on pages/store.html
> +<main>
Good use of semantic HTML tags throughout the page

2021-11-27 17:11 UTC, moneyinthesky commented on pages/store.html
> +                      <input type="text" class="fname" name="first_name"/>
Maybe you can think about validation attributes that can be added here?

2021-11-27 17:17 UTC, moneyinthesky commented
Hey @YDemirer, overall this is looking quite good, well done! If you get a chance, definitely consider adding some validation on the input fields. You can read more about this here - https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#using_built-in_form_validation. Please let me know if you have questions about this!

2021-12-02 17:29 UTC, Monika39-maker commented on css/style.css
> +    float: right;
Lucy said, 'float' property is not very much in trend anymore. so, may be not use it

2021-12-02 17:31 UTC, Monika39-maker requested changes
I added a comment. please check. and confirm it from others  fo me as well 😆

2023-09-12 08:46 UTC, closed without merging