London Class 9_Turing - Mohamed Abdalla - HTML/CSS - Week 1
CodeYourFuture/HTML-CSS-Module-Project pull request #509
Opened 2022-10-27 15:49 UTC by Mohamed-Abdalla-1

**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name: Mohamed Abdalla
- Your City: London
- Your Slack Name: Mohamed Abdalla 

# Homework Details

- Module: HTML/CSS
- Week: Week 1

# Notes

- What did you find easy?

- What did you find hard?

- What do you still not understand?

- Any other notes?

2022-10-29 12:03 UTC, Mohamed-Abdalla-1 commented
hello this is a test request

2022-11-10 07:44 UTC, Abdirizak-Mohamed commented
Hey Mohamed, 

Another awesome pull! Really good job completing Levels 1/2. Again super well structured and easy to read code. 
A couple of nitpicks for level-2. It could be worth looking @ accent-color to colour the radio buttons in the form and you look to have commented out the image on the right of the form.

2022-12-26 13:21 UTC, farzaneh-haghani commented
Your job is amazing. 👍

2022-12-26 13:27 UTC, farzaneh-haghani requested changes

2022-12-26 13:37 UTC, Mohamed-Abdalla-1 commented on css/style.css
> +  background: rgba(196, 196, 196, 0.1);
thank you

2026-09-14 08:42 UTC, closed without merging